spring.application.name=project

# Database Configuration for postgres

spring.datasource.url=jdbc:postgresql://localhost:5432/kewal_sons-db
spring.datasource.username=User
spring.datasource.password=admin123

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#file.upload-dir=./uploads

cloudinary.cloud-name=dcd6qfd39dcd6qfd39
cloudinary.api-key=311624661533629
cloudinary.api-secret=v0wy6KI69GJWp0ZsJCA9xCLKdMk

